CREATE OR REPLACE VIEW V_CATEGORY_GROUP AS (
  SELECT
    G.NAME,
    G.UUID,
    SUM(VC.AMOUNT) AS AMOUNT,
    G.ADMINISTRATOR_UUID,
    G.CATEGORY_TYPE
  FROM T_CATEGORY_GROUP G
    LEFT JOIN V_CATEGORY VC ON G.UUID = VC.CATEGORY_GROUP_UUID
  GROUP BY G.UUID);

CREATE OR REPLACE VIEW V_CATEGORY AS (
  SELECT
    C.NAME,
    C.UUID,
    C.CATEGORY_GROUP_UUID,
    SUM(S.AMOUNT) AS AMOUNT
  FROM T_CATEGORY C
    LEFT JOIN T_STATEMENT S ON S.CATEGORY_UUID = C.UUID
  GROUP BY C.UUID
);