DELETE FROM T_HISTORIC_PRICE;

CREATE TABLE T_AMOUNT_TYPE
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  AMOUNT_NAME VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX UN01_AMOUNT_TYPE ON T_AMOUNT_TYPE (NAME);

ALTER TABLE T_HISTORIC_PRICE DROP COLUMN PRICE;
ALTER TABLE T_HISTORIC_PRICE
    ADD COLUMN AMOUNT DOUBLE;

ALTER TABLE T_HISTORIC_PRICE
    ADD COLUMN AMOUNT_TYPE_UUID VARCHAR(255);

ALTER TABLE T_HISTORIC_PRICE
  ADD CONSTRAINT FK02_HISTORIC_PRICE FOREIGN KEY (AMOUNT_TYPE_UUID) REFERENCES T_AMOUNT_TYPE (UUID);

INSERT INTO T_AMOUNT_TYPE (UUID, NAME, AMOUNT_NAME) VALUES ('6ca6dbe3-84f9-486f-a6ea-5efee0f5ab1e', 'EUR', 'CURRENCY'), ('4c9a36ab-5278-420d-9ee4-fa9d03ffc8b6', 'USD', 'CURRENCY');