CREATE TABLE T_PORTFOLIO
(
    UUID VARCHAR(255) PRIMARY KEY NOT NULL
);

CREATE TABLE T_ALLOCATION
(
    UUID VARCHAR(255) PRIMARY KEY NOT NULL,
    ALLOCATION DOUBLE,
    FINANCIAL_INSTRUMENT_UUID VARCHAR(255) NOT NULL,
    PORTFOLIO_UUID VARCHAR(255),
    CONSTRAINT FK01_ALLOCATION FOREIGN KEY (FINANCIAL_INSTRUMENT_UUID) REFERENCES T_FINANCIAL_INSTRUMENT (UUID),
    CONSTRAINT FK02_ALLOCATION FOREIGN KEY (PORTFOLIO_UUID) REFERENCES T_PORTFOLIO (UUID)
);
CREATE INDEX I01_ALLOCATION ON T_ALLOCATION (FINANCIAL_INSTRUMENT_ID);
CREATE INDEX I02_ALLOCATION ON T_ALLOCATION (PORTFOLIO_ID);