CREATE TABLE T_PORTFOLIO
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT
);

CREATE TABLE T_ALLOCATION
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ALLOCATION DOUBLE,
    FINANCIAL_INSTRUMENT_ID INT(11) NOT NULL,
    PORTFOLIO_ID INT(11),
    CONSTRAINT FK01_ALLOCATION FOREIGN KEY (FINANCIAL_INSTRUMENT_ID) REFERENCES T_FINANCIAL_INSTRUMENT (ID),
    CONSTRAINT FK02_ALLOCATION FOREIGN KEY (PORTFOLIO_ID) REFERENCES T_PORTFOLIO (ID)
);
CREATE INDEX I01_ALLOCATION ON T_ALLOCATION (FINANCIAL_INSTRUMENT_ID);
CREATE INDEX I02_ALLOCATION ON T_ALLOCATION (PORTFOLIO_ID);