UPDATE T_STATEMENT SET CATEGORY_UUID = NULL;

DELETE FROM T_CATEGORY;

ALTER TABLE T_CATEGORY ADD COLUMN CATEGORY_GROUP_UUID VARCHAR(255) NOT NULL;

ALTER TABLE T_CATEGORY ADD CONSTRAINT FK02_CATEGORY FOREIGN KEY (CATEGORY_GROUP_UUID) REFERENCES T_CATEGORY_GROUP (UUID);
