CREATE TABLE T_CATEGORY_GROUP
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  ADMINISTRATOR_UUID VARCHAR(255) NOT NULL,
  CONSTRAINT FK01_CATEGORY_GROUP FOREIGN KEY (ADMINISTRATOR_UUID) REFERENCES T_PERSON (UUID)
);

CREATE INDEX I01_CATEGORY_GROUP ON T_CATEGORY_GROUP (ADMINISTRATOR_UUID);
