# DELETE FROM T_HISTORIC_PRICE;
#
# CREATE TABLE T_AMOUNT_TYPE
# (
#   ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
#   AMOUNT_NAME VARCHAR(255) NOT NULL
# );
#
# ALTER TABLE T_HISTORIC_PRICE DROP COLUMN price;
# ALTER TABLE T_HISTORIC_PRICE
#     ADD COLUMN amount DOUBLE;
#
# ALTER TABLE T_HISTORIC_PRICE
#     ADD COLUMN AMOUNT_TYPE_ID INT(11);
#
# ALTER TABLE T_HISTORIC_PRICE
#   ADD CONSTRAINT FK02_HISTORIC_PRICE FOREIGN KEY (AMOUNT_TYPE_ID) REFERENCES T_AMOUNT_TYPE (ID);
#
# INSERT INTO T_AMOUNT_TYPE (ID, AMOUNT_NAME) VALUES (1, 'EUR'), (2, 'USD');