CREATE TABLE T_PERSON
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX UN01_PERSON ON T_PERSON (USERNAME);
CREATE TABLE T_BANK
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  NAME VARCHAR(255)
);
CREATE TABLE T_BANKACCOUNT
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  NUMBER VARCHAR(255) NOT NULL,
  ADMINISTRATOR_UUID VARCHAR(255) NOT NULL,
  BANK_UUID VARCHAR(255),
  OWNER_UUID VARCHAR(255),
  CONSTRAINT FK01_BANKACCOUNT FOREIGN KEY (ADMINISTRATOR_UUID) REFERENCES T_PERSON (UUID),
  CONSTRAINT FK02_BANKACCOUNT FOREIGN KEY (BANK_UUID) REFERENCES T_BANK (UUID),
  CONSTRAINT FK03_BANKACCOUNT FOREIGN KEY (OWNER_UUID) REFERENCES T_PERSON (UUID)
);
CREATE INDEX I01_BANKACCOUNT ON T_BANKACCOUNT (BANK_UUID);
CREATE INDEX I02_BANKACCOUNT ON T_BANKACCOUNT (ADMINISTRATOR_UUID);
CREATE INDEX I03_BANKACCOUNT ON T_BANKACCOUNT (OWNER_UUID);
CREATE UNIQUE INDEX UN_BANKACCOUNT ON T_BANKACCOUNT (NUMBER, ADMINISTRATOR_UUID);
CREATE TABLE T_CAR
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  BRAND VARCHAR(255),
  FUELTYPE VARCHAR(255),
  MODEL VARCHAR(255),
  PURCHASEDATE DATE,
  PURCHASEPRICE DOUBLE,
  OWNER_UUID VARCHAR(255),
  CONSTRAINT FK01_CAR FOREIGN KEY (OWNER_UUID) REFERENCES T_PERSON (UUID)
);
CREATE INDEX I01_CAR ON T_CAR (OWNER_UUID);
CREATE TABLE T_CATEGORY
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  NAME VARCHAR(255)
);
CREATE TABLE T_FINANCIAL_INSTRUMENT
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  QUOTE VARCHAR(255)
);
CREATE UNIQUE INDEX UN01_FINANCIAL_INSTRUMENT ON T_FINANCIAL_INSTRUMENT (QUOTE);
CREATE TABLE T_FUND_PURCHASE
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  DATE DATE NOT NULL,
  NUMBEROFSHARES VARCHAR(255) NOT NULL,
  QUOTE VARCHAR(255),
  SHAREPRICE DOUBLE NOT NULL,
  TRANSACTIONCOST DOUBLE,
  PERSON_UUID VARCHAR(255),
  CONSTRAINT FK01_FUND_PURCHASE FOREIGN KEY (PERSON_UUID) REFERENCES T_PERSON (UUID)
);
CREATE INDEX I01_FUND_PURCHASE ON T_FUND_PURCHASE (PERSON_UUID);
CREATE TABLE T_HISTORIC_PRICE
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  DATE DATE,
  PRICE DOUBLE,
  FINANCIAL_INSTRUMENT_UUID VARCHAR(255) NOT NULL,
  CONSTRAINT FK01_HISTORIC_PRICE FOREIGN KEY (FINANCIAL_INSTRUMENT_UUID) REFERENCES T_FINANCIAL_INSTRUMENT (UUID)
);
CREATE UNIQUE INDEX UN_HISTORIC_PRICE_01 ON T_HISTORIC_PRICE (FINANCIAL_INSTRUMENT_UUID, DATE);
CREATE TABLE T_REFUELING
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  DATE DATE,
  KILOMETRES DOUBLE,
  LITERS DOUBLE,
  PRICE DOUBLE,
  PRICEPERLITER DOUBLE,
  CAR_UUID VARCHAR(255),
  FUELTANKFULL BIT(1) NOT NULL ,
  CONSTRAINT FK01_REFUELING FOREIGN KEY (CAR_UUID) REFERENCES T_CAR (UUID)
);
CREATE INDEX I01_REFUELING ON T_REFUELING (CAR_UUID);
CREATE TABLE T_STATEMENT
(
  UUID VARCHAR(255) PRIMARY KEY NOT NULL,
  AMOUNT DECIMAL(19,2),
  DATE DATE,
  DESTINATIONACCOUNT_UUID VARCHAR(255),
  ORIGINATINGACCOUNT_UUID VARCHAR(255),
  CONSTRAINT FK01_STATEMENT FOREIGN KEY (DESTINATIONACCOUNT_UUID) REFERENCES T_BANKACCOUNT (UUID),
  CONSTRAINT FK02_STATEMENT FOREIGN KEY (ORIGINATINGACCOUNT_UUID) REFERENCES T_BANKACCOUNT (UUID)
);
CREATE INDEX I01_STATEMENT ON T_STATEMENT (DESTINATIONACCOUNT_UUID);
CREATE INDEX I02_STATEMENT ON T_STATEMENT (ORIGINATINGACCOUNT_UUID);