DELETE FROM T_HISTORIC_PRICE;

CREATE TABLE T_AMOUNT_TYPE
(
  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  AMOUNT_NAME VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX UN01_AMOUNT_TYPE ON T_AMOUNT_TYPE (NAME);

ALTER TABLE T_HISTORIC_PRICE DROP COLUMN PRICE;
ALTER TABLE T_HISTORIC_PRICE
    ADD COLUMN AMOUNT DOUBLE;

ALTER TABLE T_HISTORIC_PRICE
    ADD COLUMN AMOUNT_TYPE_ID INT(11);

ALTER TABLE T_HISTORIC_PRICE
  ADD CONSTRAINT FK02_HISTORIC_PRICE FOREIGN KEY (AMOUNT_TYPE_ID) REFERENCES T_AMOUNT_TYPE (ID);

INSERT INTO T_AMOUNT_TYPE (ID, NAME, AMOUNT_NAME) VALUES (1, 'EUR', 'CURRENCY'), (2, 'USD', 'CURRENCY');